Section "InputClass"
    Identifier      "generic mouse for Chromium OS"
    MatchIsPointer  "on"
    MatchDevicePath "/dev/input/event*"
    Driver          "cmt"
    Option          "Mouse Accel Curves" "1"
    Option          "Mouse Scroll Curves" "1"
EndSection

Section "InputClass"
    Identifier      "Evdev for Elo TouchScreen"
    # For Elo TouchSystems 2700 IntelliTouch(r). This is a single touch device
    # and we simulate it as a mouse pointer.
    MatchUSBID      "04e7:0020"
    MatchDevicePath "/dev/input/event*"
    Driver          "evdev"
    # This should make X configure the device as pointer instead of keyboard
    Option          "IgnoreAbsoluteAxes" "false"
    # We want a slave pointer, rather than floating slave.
    Option          "SendCoreEvents" "true"
    Option          "Calibration"     "55 4075 80 4060"
    Option          "InvertY"         "1"
    Option          "InvertX"         "1"
EndSection
