Section "InputClass"
    Identifier      "generic mouse for Chromium OS"
    MatchIsPointer  "on"
    MatchDevicePath "/dev/input/event*"
    Driver          "cmt"
    Option          "Mouse Accel Curves" "1"
    Option          "Mouse Scroll Curves" "1"

    # CMT devices potentially process keyboard events
    Option          "XkbModel" "pc"
    Option          "XkbLayout" "us"

    Option          "Accel Min dt" "0.0001"
EndSection

Section "InputClass"
    Identifier      "Evdev for Elo TouchScreen"
    # For Elo TouchSystems 2700 IntelliTouch(r). This is a single touch device
    # and we simulate it as a mouse pointer.
    MatchUSBID      "04e7:0020"
    MatchDevicePath "/dev/input/event*"
    Driver          "evdev"
    # This should make X configure the device as pointer instead of keyboard
    Option          "IgnoreAbsoluteAxes" "false"
    # We want a slave pointer, rather than floating slave.
    Option          "SendCoreEvents" "true"
    Option          "Calibration"     "55 4075 80 4060"
    Option          "InvertY"         "1"
    Option          "InvertX"         "1"
EndSection

# Prevent ABS_MISC messages from going to Chrome. These contain battery
# status, but currently look like mouse movement to Chrome.
# There are two remotes, so we whitelist both
Section "InputClass"
    Identifier      "Evdev for GVC Remote 0471:21cc"
    MatchUSBID      "0471:21cc"
    MatchDevicePath "/dev/input/event*"
    Driver          "evdev"
    Option          "IgnoreAbsoluteAxes" "true"
EndSection

Section "InputClass"
    Identifier      "Evdev for GVC Remote 0471:20d9"
    MatchUSBID      "0471:20d9"
    MatchDevicePath "/dev/input/event*"
    Driver          "evdev"
    Option          "IgnoreAbsoluteAxes" "true"
EndSection

Section "InputClass"
    Identifier      "Odie Gamepad should be ignored"
    MatchUSBID      "18d1:2c40"
    MatchDevicePath "/dev/input/event*"
    Option          "Ignore" "true"
EndSection
