Section "InputClass"
    Identifier "non-core touchscreen catchall"
    MatchIsTouchscreen "on"
    MatchDevicePath "/dev/input/event*"
    Option "SendCoreEvents" "false"
EndSection

Section "InputClass"
    Identifier "Atmel touchscreen"
    MatchIsTouchscreen "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "Atmel"
    Option "EnableTouchNoiseFilter" "1"
EndSection

