Section "InputClass"
    Identifier      "touchpad orco elan"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "Elan"
    Option          "Integrated Touchpad" "1"
    Option          "Touchpad Stack Version" "2"
    # Pressure calibration results:
    # Probe Diameter   Measured   Expected   Calibrated
    # 0     3.90       39.22      11.95      2.23
    # 1     5.70       43.64      25.52      18.23
    # 2     7.70       51.56      46.57      46.83
    # 3     9.90       60.18      76.98      77.97
    # 4     11.70      72.72      107.51     123.26
    # 5     13.90      84.02      151.75     164.11
    # 6     17.80      116.78     248.85     282.46
    Option          "Pressure Calibration Offset" "-139.4510508"
    Option          "Pressure Calibration Slope" "3.61285004831"
EndSection