Section "InputClass"
    Identifier      "touchpad oak elan"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "Elan"
    Option          "Integrated Touchpad" "1"
    Option          "Touchpad Stack Version" "2"
    Option          "Pressure Calibration Offset" "-232.615476471713"
    Option          "Pressure Calibration Slope" "4.5003322861445"
    Option          "Tap Minimum Pressure" "25.0"

    # Resolution is not correctly reported by the device.
    Option          "Horizontal Resolution" "30"
    Option          "Vertical Resolution" "28"
EndSection
