# Configure touchpads to use Chromium Multitouch (cmt) X input driver
Section "InputClass"
    Identifier      "touchpad kip"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "Elan"

    Option          "Integrated Touchpad" "1"
    Option          "Touchpad Stack Version" "1"

    Option          "Pressure Calibration Offset" "-144.44924745909"
    Option          "Pressure Calibration Slope" "3.366831045"
    # Disable some causes of delay
    Option          "IIR b0" "1"
    Option          "IIR b1" "0"
    Option          "IIR b2" "0"
    Option          "IIR b3" "0"
    Option          "IIR a1" "0"
    Option          "IIR a2" "0"
    Option          "IIR Distance Threshold" "1000"
    Option          "Input Queue Delay" "0"

    # A temporary fix for resolution. Should be removed after Elan has
    # fixed them in the firmware.
    Option          "Horizontal Resolution" "30"
    Option          "Vertical Resolution" "29"
EndSection
