# Dratini/Dragonair/Jinlon
Section "InputClass"
    Identifier      "touchpad hatch elan"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "Elan"
    MatchUSBID      "04f3:00c5|04f3:00ac"
    Option          "Zero Finger Click Enable" "0"
EndSection
