# Configure touchpads to use Chromium Multitouch (cmt) X input driver
Section "InputClass"
    Identifier      "touchpad daisy"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "Atmel|cyapa"
    Option          "Integrated Touchpad" "1"
    # Disable some causes of delay
    Option          "IIR b0" "1"
    Option          "IIR b1" "0"
    Option          "IIR b2" "0"
    Option          "IIR b3" "0"
    Option          "IIR a1" "0"
    Option          "IIR a2" "0"
    Option          "IIR Distance Threshold" "1000"
    Option          "Input Queue Delay" "0"
EndSection

Section "InputClass"
    Identifier      "touchpad daisy cyapa"
    MatchIsTouchpad "on"
    MatchProduct    "Cypress APA Trackpad (cyapa)"
    MatchDevicePath "/dev/input/event*"
    Option          "Integrated Touchpad" "1"
    Option          "Pressure Calibration Offset" "-1.73338827637399"
    Option          "Pressure Calibration Slope" "2.06326787767144"
    # Extra filters for Daisy
    Option          "Box Width" "1.0"
    Option          "Sensor Jump Filter Enable" "1"
    Option          "Sensor Jump Min Dist Non-Move" "0.3"
    Option          "Sensor Jump Min Dist Move" "0.9"
    Option          "Sensor Jump Similar Multiplier Move" "1.5"
    Option          "Split Merge Max Movement" "6.5"
    Option          "Merge Max Ratio" "0.5"
    Option          "Max Allowed Pressure Change Per Sec" "4000"
    Option          "Max Hysteresis Pressure Per Sec" "4000"
    # The flexible case can cause accidental physical clicks
    Option          "Zero Finger Click Enable" "0"
    Option          "Delay On Possible Liftoff" "1"
    Option          "Input Queue Max Delay" "0.019"
    Option          "Split Corrector Enabled" "1"
EndSection

Section "InputClass"
    Identifier      "touchpad daisy_spring atmel"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "Atmel"
    Option          "Pressure Calibration Offset" "-24.7357019600736"
    Option          "Pressure Calibration Slope" "2.99088029937309"
    # TODO(clchiou): Calibrate bias on X-axis
    Option          "Touchpad Device Output Bias on X-Axis" "26.68917773528923"
    Option          "Touchpad Device Output Bias on Y-Axis" "26.68917773528923"
    # We see lots of pressure changes under normal use, so raise thresholds
    Option          "Max Allowed Pressure Change Per Sec" "100000.0"
    Option          "Max Hysteresis Pressure Per Sec" "100000.0"
    Option          "Fling Buffer Suppress Zero Length Scrolls" "1"
    # People complain that light tap clicks don't register
    Option          "Tap Minimum Pressure" "21.0"
    Option          "Box Width" "0.3"
    # Fix for finger merge issue
    Option          "Finger Merge Filter Enabled" "1"
EndSection
