# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# kappa/burnet/esche
Section "InputClass"
    Identifier      "touchpad jacuzzi elan"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "Elan"
    MatchUSBID      "04f3:00d1|04f3:0102|04f3:0103"
    Option          "Zero Finger Click Enable" "0"
EndSection
