# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Berknip/Dirinboz
Section "InputClass"
    Identifier      "touchpad zork elan"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "Elan"
    MatchUSBID      "04f3:00E9|04f3:008E"
    Option          "Zero Finger Click Enable" "0"
EndSection
