# Configure touchpads to use Chromium Multitouch (cmt) X input driver
Section "InputClass"
    Identifier      "touchpad eve"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "ACPI0C50:00 18D1:5028 Touchpad"

    Option          "Pinch Enable" "1"
EndSection
