# Configure touchpads to use Chromium Multitouch (cmt) X input driver
Section "InputClass"
    Identifier      "touchpad samus"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "Atmel"
    Option          "Touchpad Stack Version" "2"
    Option          "Integrated Touchpad" "1"
    Option          "Pressure Calibration Offset" "-22.7836164477699"
    Option          "Pressure Calibration Slope" "1.174571775"
    Option          "Tap Minimum Pressure" "5.0"
    Option          "Vertical Resolution" "8"
    Option          "Horizontal Resolution" "9"

    # Enable Stationary Wiggle Filter
    Option          "Stationary Wiggle Filter Enabled" "1"
    Option          "Finger Moving Energy" "0.06"
    Option          "Finger Moving Hysteresis" "0.03"
EndSection 
