# kappa
Section "InputClass"
    Identifier      "touchpad jacuzzi elan"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "Elan"
    MatchUSBID      "04f3:00d1"
    Option          "Zero Finger Click Enable" "0"
EndSection
